name: Continuous Integration

on:
  push:
    branches-ignore:
      - main
      - develop
      - gh-pages
  pull_request:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  ci:
    uses: wael-jaber/task-checklist-app/.github/workflows/ci-reusable.yml@develop
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
