name: Continuous Integration

on:
  push:
    branches-ignore:
      - main
      - develop
      - gh-pages
  pull_request:

jobs:
  ci:
    uses: wael-jaber/task-checklist-app/.github/workflows/ci-reusable.yml@develop
